# Generated by Django 6.0 on 2025-12-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proacademico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Pendente', max_length=10),
        ),
    ]
