# Generated by Django 6.0 on 2025-12-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proacademico', '0002_obra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoobra',
            name='arquivo',
            field=models.FileField(upload_to='arquivos/obras/%Y/%m/%d/'),
        ),
    ]
